project:
  type: website
  output-dir: docs
website:
  title: "seanteachesmath"
  navbar:
    right:
      - about/index.qmd
      - teaching/index.qmd
      - icon: github
        href: https://github.com/seanteachesmath
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: source

