---
title: "The Sorrow of AI"
author: "Sean Laverty"
date: "2025-03-10"
categories: [teaching]
---

# The Sorrow of AI

## The Scene

A man sits down at a faculty development event *The future of AI in education*. 

...

*Moderator:* And any questions?

*Me:* Just one, "What's the point?"

*Panelist (shifts, awkwardly):* Sorry, can you expand?

Me: What is the minimum unit of knowledge in your discipline that a person must posess in order to responsibly interpret and apply the result of a generative AI conversation? How are we supposed to agree on that? Why does *that* "conversation" need to happen in the first place?" What level of Bloom's Taxonomy is that?!?

## The loneliness epidemic

We are supposed to be encouraging much-needed interaction, but instead are encouraged to outsource questions and answers, emails, and office hours visits to a chat bot. So much for the serendipity of a quick question about homework, that just as quickly turns into a long-term student project.  An arbitrary number of supporting links to follow, but there is abundant evidence that people, especially our students are struggling with social interactions. Why rob them of that practice?

I have watched students hold a conversation through cells of a shared spreadsheet document, while seated just feet apart.  There is nothing wrong with that, but one of the subtle goals of this particular class was to provide practice with a variety of forms of communication.  And, to be clear, this was not one I had intended for them to pratics. 

Potential environmental impacts aside, well, maybe not just yet -- power a new data center, Microsoft made a deal to open the nuclear power plant just a few miles from where I grew up, that, just a few years before I was born, experienced a partial meltdown. But, *nuclear power to keep up with AI*, is a horrifying concession.

## The disruption

*"But you know they said that the (graphing) calculator was this disruptive in its time."*

But my calculator ran on a watch battery and a small solar cell.  The graphing calculator, a story in itself, has neither improved, nor gone down in price, since then.  The story is "we didn't have enough money to buy one while I was in high school, or I was too afraid to ask money questions at home, so I borrowed one from the school (during the school day only)". Later and in preparation for college, as a high school graduation present, I was given a translucent Texas Instruments TI-83 Plus, in silver.

As often is the case with many college students, I wasn't really allowed to use it for much in class anyway.  Today, it pretty much sits in my desk drawer unused, and as long as the batteries work (just 4 AAA or AA batteries), it's free to borrow at any time. Now *teaching* college math, rather than *taking* it, I am always disappointed to see students expected or expecting to use graphing calculators, what terrible devices.

Back to the main point. Our obsession with tools.  Graphing calculators aren't inherently terrible, they are just currently overpriced and somewhat inflexible.  Now there are a variety of freely-available graphical (e.g., <https://desmos.org>) or computational (e.g., <https://cocalc.org>) tools for use on phones, tablets, and laptops.  

Ironically, we have often limited our, and our students', available tools to decades-old technology. Yet, suddenly, we have gone from a lifetime of use on a watch battery and solar cell, to something on the order of a half a liter of water for every 100 words of email.

We are plagued by the pursuit of innovation, when sometimes we should just stick to ["stuff that works"](<https://www.youtube.com/watch?v=2mprD2MN5vo>). Does AI have a place in higher education, sure? I just don't want to hear about it every single day and in every single setting.

Thinking of "stuff that works", good solid fundamentals, made me think of this table^[Recreated from: _Are Biologists Getting the Mathematical Training They Need in College?_ 
Jill A. Marshall and Pablo Durán. Volume 46, Number 6, November/December 2018, Pages 612–618.]

|Training needed | MAA | NRC | AAAS | Consensus |
| --- | --- | --- | --- | --- |
|Descriptive statistics | x | x | x | X |
|Inferential statistics | x | x | x | X |
|Multivariate statistics | x |  |  |  |
|Precalculus (functions, graphical representations) | x | x | x | X |
|Discrete mathematics, matrix algebra, qualitative graphs | x | x | | |
|Calculus topics: rates of change, summation, optimization | x | x | | |
|Series | | x | | |
|Differential equations | | x | | |
|Dynamical systems (continuous, discrete) | x | x | x | X |
|Modeling/simulation | x | x | x | X |
|Stochastic processes | x | x | x | X |

This suggests that people have pretty lofty goals but are willing to stand on pretty rickety ladders to reach towards them.  It's hard to imagine *confidently* working with or understanding stochastic processes and dynamical systems as mathematical models, as those depend on differential, linear algebra, and calculus, and not necessarily in any particular order.

Even listing these topics in order hides the truth, they are their best when interconnected, jumbled, even connected to other new things.  Pilots and surgeons should use checkboxes, perhaps not everyone else, or at least not *for* everything else. But we have learned nothing if we proceed one step at a time, answer by answer, asking for, but not thinking about the answer. We miss the connections.

## Generative AI and the future of higher education

Wasn't learning the fun part? Any time some sort of cheating incident occurs, the refrain begins "it wasn't about the answer, it was about the process."  The emphasis isn't on the final product as much as it is the research process, the note-taking, the accidental learning along the way.  Ideally, even the understanding of the process itself. With AI-heavy teaching or learning, what is the process? Typing some words, to get other words which are then copied and pasted? What is gained? What is lost? Aside from the electricity, the water, the interaction, the opportunity for potentially-life shifting advice at any moment, and quite possibly, the truth.

The longer you do or teach something like math, if you really think about it, you become skeptical of some of its conventions.  Pages and pages of "answers" in the form of integral tables to begin or end the book.  Thinking is the fun part, not matching problem to answer. I am thinking here of a student that once requested I take a look at a grade after they had impressively used a memorized table of integrals to simply write down the answer to the question, more briefly and in a slightly different form than I was expecting. But, in doing so, missed the opportunity to demonstrate the process which illustrated _why_ the solution emerged.

By thinking just one problem at a time, this student, as have many others, missed out on understanding how that problem fit into the context of others like it. That's the learning.

## Conclusion

Thinking is the fun part, right? I get that we ultimately find ourselves "checking answers" and those wind up shaping grades, but the answer is just sort of an indicator of the practice and work that came before it. The process is so much more enjoyable, for everyone, when we are all on the same team.

